from marshmallow import Schema, fields


class RiskProfileSchema(Schema):
    iprm_id = fields.Int(load_from='IPRM Questionnaire ID')
    cpr_type = fields.Str(load_from='CRP Type')
    compliance_rating_status = fields.Str(load_from='Compliance Rating Status')
    sdlc_path = fields.Str(load_from='SDLC Path')
    dr_rto_tier = fields.Str(load_from='DR/RTO Tier')
    sox_value = fields.Bool(load_from='SOX Value')
    gxp = fields.Bool(load_from='GxP?')
    gcp = fields.Bool(load_from='GCP?')
    gdp = fields.Bool(load_from='GDP?')
    glp = fields.Bool(load_from='GLP?')
    gmp = fields.Bool(load_from='GMP?')
    gpvp = fields.Bool(load_from='GPvP?')
    eea_pi_spi = fields.Bool(load_from='EEA PI/SPI')
    ma201 = fields.Bool(load_from='MA 201')
    sales = fields.Bool(load_from='Sales')
    aca = fields.Bool(load_from='ACA')
    smd = fields.Bool(load_from='SMD')
    data_class = fields.Str(load_from='Data Classification')
    cybersecurity_protection_level = fields.Str(load_from='Cybersecurity Protection Level')
    access = fields.Bool(load_from='Access?')
    detect = fields.Bool(load_from='Detect?')
    identify = fields.Bool(load_from='Identify?')
    prevent = fields.Bool(load_from='Prevent?')
    response = fields.Bool(load_from='Response?')
    regional = fields.Bool(load_from='Regional')
    globals = fields.Bool(load_from='Global')
    is_auth = fields.Str(load_from='I&AM Authentication')


class EnvironmentSchemas(Schema):
    ciid = fields.Str(load_from='\ufeffCIID')
    name = fields.Str(load_from='Deployment Name')
    description = fields.Str(load_from='Deployment Description')
    status = fields.Str(load_from='')
    env_type = fields.Str(load_from='Env. Type')
    app_deployment_type = fields.Str(load_from='Application Deployment Type')
    location = fields.Str(load_from='Location')
    org_level_1 = fields.Str(load_from='Org Level 1')
    org_level_2 = fields.Str(load_from='Org Level 2')
    org_level_3 = fields.Str(load_from='Org Level 3')
    business_critical = fields.Bool(default=True, load_from='Business Critical')
    iprm_info = fields.Nested(RiskProfileSchema)
    used_in_lab = fields.Bool(load_from='Used in Lab?')
    ci_mgmt_group = fields.Str(load_from='CI Mgmt Group')
    under_change_mgmt = fields.Bool(load_from='Under Change Mgmt?')
    sla_support_id = fields.Str(load_from='SLA Support ID')
    primary_url = fields.Url(load_from='Primary URL')
    key_used_periods = fields.Str(load_from='Key Use Periods')
    app_externally_accessible = fields.Bool(load_from='Application Externally Accessible')
    externally_hosted_app = fields.Bool(load_from='Externally Hosted Application')
    country_solution_hosted_in = fields.Str(load_from='Country Solution Hosted In')
    hosting_vendor = fields.Str(load_from='Hosting Vendor')
    daily_monitoring_site = fields.Str(load_from='Daily Monitoring of Site')
    cookies_stored = fields.Bool(load_from='Cookies Stored?')
    customer_into_stored = fields.Bool(load_from='Customer Info Stored?')


class MasterSchema(Schema):
    ciid = fields.Str(load_from='Master CI ID')
    application = fields.Str(load_from='Master Application')
    environments = fields.Nested(EnvironmentSchemas, many=True)
